export const appStrings = {
  en: {
    checking: 'Connecting to the server…', waiting: 'The server may need a moment to wake up.',
    timeout: 'The server is taking too long to respond. Try again in a moment.',
    failed: 'Could not connect to the server. Check your connection and try again.',
    needsKey: 'Enter the access key to continue.', retry: 'Try again', language: 'Language',
    check: 'Check connection', checkingConnection: 'Checking connection…',
    health: { ok: 'The TV provider is reachable.', provider_rejected: 'The TV provider refused access. Check the subscription or connection with your provider.', proxy_unreachable: 'The connection to the TV provider is unavailable. Check that the home device is online.', timeout: 'The TV provider did not respond in time. Try again shortly.', not_configured: 'The TV connection needs to be configured.', unknown: 'Could not confirm the TV connection. Try again shortly.' },
    healthNote: 'This checks access to the provider. An individual channel may still be unavailable.',
    title: 'Connect your TV account', server: 'Server', username: 'Username', password: 'Password',
    required: 'All three fields are required.', connecting: 'Connecting…', connect: 'Connect',
    keyTitle: 'Access key required', keyDescription: 'Enter your access key to continue.', key: 'Access key', save: 'Save & retry', cancel: 'Cancel',
  },
  he: {
    checking: 'מתחבר לשרת…', waiting: 'ייתכן שהשרת זקוק לרגע כדי להתעורר.',
    timeout: 'השרת לא ענה בזמן. אפשר לנסות שוב בעוד רגע.', failed: 'לא ניתן להתחבר לשרת. בדוק את החיבור ונסה שוב.',
    needsKey: 'הזן מפתח גישה כדי להמשיך.', retry: 'נסה שוב', language: 'שפה',
    check: 'בדיקת חיבור', checkingConnection: 'בודק את החיבור…',
    health: { ok: 'ספק הטלוויזיה נגיש.', provider_rejected: 'ספק הטלוויזיה סירב לגישה. בדוק את המנוי או את החיבור מול הספק.', proxy_unreachable: 'החיבור לספק הטלוויזיה אינו זמין. בדוק שהמכשיר הביתי מחובר.', timeout: 'ספק הטלוויזיה לא ענה בזמן. נסה שוב בעוד רגע.', not_configured: 'נדרשת הגדרה של חיבור הטלוויזיה.', unknown: 'לא ניתן לאמת את החיבור כרגע. נסה שוב בעוד רגע.' },
    healthNote: 'הבדיקה מאמתת גישה לספק. ייתכן שערוץ מסוים עדיין אינו זמין.',
    title: 'חיבור לחשבון הטלוויזיה', server: 'שרת', username: 'שם משתמש', password: 'סיסמה',
    required: 'יש למלא את כל שלושת השדות.', connecting: 'מתחבר…', connect: 'התחבר',
    keyTitle: 'נדרש מפתח גישה', keyDescription: 'הזן את מפתח הגישה שלך כדי להמשיך.', key: 'מפתח גישה', save: 'שמור ונסה שוב', cancel: 'ביטול',
  },
  ar: {
    checking: 'جارٍ الاتصال بالخادم…', waiting: 'قد يحتاج الخادم إلى لحظة لبدء التشغيل.',
    timeout: 'لم يستجب الخادم في الوقت المحدد. حاول بعد قليل.', failed: 'تعذر الاتصال بالخادم. تحقق من الاتصال وحاول مجددًا.',
    needsKey: 'أدخل مفتاح الوصول للمتابعة.', retry: 'حاول مجددًا', language: 'اللغة',
    check: 'فحص الاتصال', checkingConnection: 'جارٍ فحص الاتصال…',
    health: { ok: 'مزود التلفزيون متاح.', provider_rejected: 'رفض مزود التلفزيون الوصول. تحقق من الاشتراك أو الاتصال مع المزود.', proxy_unreachable: 'الاتصال بمزود التلفزيون غير متاح. تحقق من اتصال الجهاز المنزلي.', timeout: 'لم يستجب مزود التلفزيون في الوقت المحدد. حاول بعد قليل.', not_configured: 'يجب إعداد اتصال التلفزيون.', unknown: 'تعذر التأكد من الاتصال الآن. حاول بعد قليل.' },
    healthNote: 'يفحص هذا الاختبار الوصول إلى المزود. قد تبقى قناة معينة غير متاحة.',
    title: 'الاتصال بحساب التلفزيون', server: 'الخادم', username: 'اسم المستخدم', password: 'كلمة المرور',
    required: 'يرجى ملء الحقول الثلاثة.', connecting: 'جارٍ الاتصال…', connect: 'اتصال',
    keyTitle: 'مفتاح الوصول مطلوب', keyDescription: 'أدخل مفتاح الوصول للمتابعة.', key: 'مفتاح الوصول', save: 'حفظ وإعادة المحاولة', cancel: 'إلغاء',
  },
};
