export const playerStrings = {
  en: {
    back: 'Back', backToChannels: 'Back to channels', loading: 'Loading', paused: 'Paused',
    retrying: 'Reconnecting', retry: 'Try again', buffering: 'Buffering…',
    previous: 'Previous channel', next: 'Next channel', play: 'Play', pause: 'Pause',
    volumeDown: 'Volume down', volumeUp: 'Volume up', mute: 'Mute', sound: 'Tap for sound',
    showControls: 'Show player controls', audioUnsupported: 'Audio is not supported on this channel',
    unsupportedBrowser: 'This browser cannot run the player. A browser with WebCodecs and OffscreenCanvas is required.',
    videoUnsupported: 'This browser cannot decode this channel’s video format. Try another channel.',
    videoStalled: 'Video did not start. Try again or choose another channel. This browser may not support its video format.',
    offline: 'The internet connection is offline. Playback will retry when the connection returns.',
    timeout: 'The stream stopped responding. Check the connection and try again.',
    forbidden: 'The service refused playback. Check your access link and provider account.',
    unavailable: 'This channel is currently unavailable. Try again or choose another channel.',
    connection: 'The stream connection failed. Check the home connection and try again.',
    failed: 'Playback stopped. Try again to reconnect to the live stream.',
  },
  he: {
    back: 'חזרה', backToChannels: 'חזרה לערוצים', loading: 'טוען', paused: 'מושהה',
    retrying: 'מתחבר מחדש', retry: 'נסה שוב', buffering: 'טוען את השידור…',
    previous: 'הערוץ הקודם', next: 'הערוץ הבא', play: 'נגן', pause: 'השהה',
    volumeDown: 'הנמכת עוצמה', volumeUp: 'הגברת עוצמה', mute: 'מושתק', sound: 'גע להפעלת שמע',
    showControls: 'הצגת כפתורי הנגן', audioUnsupported: 'השמע בערוץ הזה אינו נתמך',
    unsupportedBrowser: 'הדפדפן הזה אינו תומך בנגן. נדרש דפדפן עם WebCodecs ו־OffscreenCanvas.',
    videoUnsupported: 'הדפדפן אינו יכול לפענח את פורמט הווידאו של הערוץ הזה. אפשר לנסות ערוץ אחר.',
    videoStalled: 'התמונה לא התחילה. אפשר לנסות שוב או לבחור ערוץ אחר. ייתכן שהדפדפן אינו תומך בפורמט הווידאו.',
    offline: 'אין חיבור לאינטרנט. הניגון ינסה להתחבר מחדש כשהחיבור יחזור.',
    timeout: 'השידור הפסיק להגיב. בדוק את החיבור ונסה שוב.',
    forbidden: 'השירות סירב לנגן. בדוק את קישור הגישה ואת החשבון אצל הספק.',
    unavailable: 'הערוץ אינו זמין כרגע. אפשר לנסות שוב או לבחור ערוץ אחר.',
    connection: 'החיבור לשידור נכשל. בדוק את החיבור הביתי ונסה שוב.',
    failed: 'הניגון נעצר. נסה שוב כדי להתחבר לשידור החי.',
  },
  ar: {
    back: 'رجوع', backToChannels: 'العودة إلى القنوات', loading: 'جارٍ التحميل', paused: 'متوقف مؤقتًا',
    retrying: 'جارٍ إعادة الاتصال', retry: 'حاول مجددًا', buffering: 'جارٍ تحميل البث…',
    previous: 'القناة السابقة', next: 'القناة التالية', play: 'تشغيل', pause: 'إيقاف مؤقت',
    volumeDown: 'خفض الصوت', volumeUp: 'رفع الصوت', mute: 'مكتوم', sound: 'المس لتشغيل الصوت',
    showControls: 'إظهار أدوات المشغل', audioUnsupported: 'الصوت غير مدعوم في هذه القناة',
    unsupportedBrowser: 'هذا المتصفح لا يدعم المشغل. يلزم متصفح يدعم WebCodecs وOffscreenCanvas.',
    videoUnsupported: 'لا يستطيع المتصفح فك ترميز فيديو هذه القناة. جرّب قناة أخرى.',
    videoStalled: 'لم يبدأ الفيديو. حاول مجددًا أو اختر قناة أخرى. قد لا يدعم المتصفح صيغة الفيديو.',
    offline: 'لا يوجد اتصال بالإنترنت. ستتم إعادة المحاولة عند عودة الاتصال.',
    timeout: 'توقف البث عن الاستجابة. تحقق من الاتصال وحاول مجددًا.',
    forbidden: 'رفضت الخدمة تشغيل البث. تحقق من رابط الوصول وحسابك لدى المزوّد.',
    unavailable: 'هذه القناة غير متاحة حاليًا. حاول مجددًا أو اختر قناة أخرى.',
    connection: 'فشل الاتصال بالبث. تحقق من الاتصال المنزلي وحاول مجددًا.',
    failed: 'توقف التشغيل. حاول مجددًا للاتصال بالبث المباشر.',
  },
};
